"""changed user back to username for a test

Revision ID: 437df6c273b7
Revises: f0b9bbcc2cb1
Create Date: 2023-10-06 15:47:27.191533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '437df6c273b7'
down_revision = 'f0b9bbcc2cb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.String(), nullable=True))
        batch_op.drop_constraint('fk_posts_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_posts_user_users'), 'users', ['user'], ['username'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_posts_user_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_posts_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.drop_column('user')

    # ### end Alembic commands ###
