"""added relationship to comments

Revision ID: 98a61441e330
Revises: 33fbf00e344c
Create Date: 2023-10-08 21:14:47.841002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98a61441e330'
down_revision = '33fbf00e344c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_comments_post_id_posts'), 'posts', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comments_post_id_posts'), type_='foreignkey')
        batch_op.drop_column('post_id')

    # ### end Alembic commands ###
