"""backref users to user

Revision ID: d4ce4bb6e8a6
Revises: e39812c82046
Create Date: 2023-10-06 15:29:31.463861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4ce4bb6e8a6'
down_revision = 'e39812c82046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.String(), nullable=True))
        batch_op.drop_constraint('fk_posts_username_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_posts_user_users'), 'users', ['user'], ['id'])
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_posts_user_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_posts_username_users', 'users', ['username'], ['username'])
        batch_op.drop_column('user')

    # ### end Alembic commands ###
