"""added relationship between user and posts

Revision ID: e39812c82046
Revises: d01e7dfedc9c
Create Date: 2023-10-05 12:35:48.455225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e39812c82046'
down_revision = 'd01e7dfedc9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_posts_username_users'), 'users', ['username'], ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_posts_username_users'), type_='foreignkey')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
